### PR TITLE
Allow bot flags and close #146

### PR DESCRIPTION
**Pull request by mfrasca**

### CODE REVIEW

**Comment by mfrasca** [comment]
closes #146

**Comment by mfrasca** [comment]
to update ghini to this branch:

    @echo off
    cd "%HOMEDRIVE%%HOMEPATH%"\Local\github\Ghini\ghini.desktop
    git checkout ghini-1.0-mrbg

after which you can run the script `ghini-update.bat`, to be found at https://github.com/Ghini/ghini.desktop/blob/master/scripts/ghini-update.bat.

**Comment by tmyersdn** [comment]
Good, you two seem to have some agreement.

Regarding "flag" names (which I know as "tag" names) - do either of you have a link to current info from ABCD which explains the approved use of the species field (or whatever it is called, it is specificEpithet on DarwinCore).  Please can you post the link here :) Sorry, the ABCD help portal has defeated me!

@mfrasca , I think @RoDuth is technically right on the use of the Species Epithet field to hold "tag names". Both ITF2 and HISPID say that if **“the plant represents a new species which has not been formally described, then sp. nov., sp. A, sp. 1 (or other acceptable codes) should be entered, if possible followed by a unique identifier, such as the collector's name and number or the locality. The following Species Author field must be left unfilled.”**

But I do strongly agree with you that this messes with formatting. One option as you say is to have a separate field to hold the tag name. This is in fact the method I am used to, and it works well. It allows you to keep the "tag name" in plain text instead of italics. Mario, there are a number of name qualifying fields which I believe are useful, such as to indicate if a plant is threatened, or a restricted weed, or if there is a commercial name different to the original cultivar name (it does happen). So, at some point it would be good to open this discussion up.

**Comment by tmyersdn** [comment]
... these names are called "un-named clones", and they are a valid part of Botany.

**Comment by mfrasca** [comment]
I think we are reading the ITF2 and ABCD documentation differently, and this reminds me of a different group of botanists, I think it was in Italy: they seemed to consider their file exchange and official reports formats as a formal description of how to organize the database and said that the software I was offering them did not match their needs (being the database organized differently than their intended formats).
in my view of software development, users need a usable user interface, and developers need users to understand what users are used to. 
in my experience of software development though, users tend to ask for a specific solution, often provided as software technical details or even as source code, without letting the developer (who might happen to be a professional information analyst) understand the issues at hand. this provides for suboptimal solutions and reduced flexibility. and it puts unit tests coverage in jeopardy.
in my opinion the best way to achieve a close to optimal solution is by letting a developer observe and analyze the work being done (or the software being used) by a user. this implies the developer being physically there at the user's premises. with geographically distributed development this is difficult to achieve, unfortunately.
a beautiful solution would be to have users who can write unit tests! :wink:

**Pull request merged**
