### PR TITLE
Xsl changes

### PR DESCRIPTION
**Pull request by RoDuth**
Close this if you're not interested...

You have asked for examples xsl templates, I have included a few here, but you will need the other changes for them to work.

The 2 `list_notes...` versions are just a slight rework of one of Brett's originals but demonstrate how you may use the 2 versions of notes.  They also show simple examples of templates that could be used at species, accession or plant level with differing but relevant results.  To clarify why the 2 methods: abcd only allows a single element (i.e. a block of text), this is a pain to parse in xsl so I added a 'Notes' element with sub-elements named after each notes' category.  This is similar to the way the label_distribution is included (only if used `for_labels` and not part of the abcd namespace).

the other 2 examples are adapted from how we currently do labels.  The logic for variable font size dependent on the botanic name is clunky but it works for us.  I've added the ability to add extra files (in this case images) by including them in a directory beside the template with the same name as the template. (images included in the example are public domain from [here](http://www.publicdomainfiles.com/show_file.php?id=13494517212891) and [here](https://en.wikipedia.org/wiki/Hammer_and_pick)) for the memorial version to work you need a note of category 'memorial tree no' (or 'memorial_tree_no') that contains just a number and another category 'memorial name' with a name. We add these to a plant and print the reports from the plant source type.

`abcd_2.06.xsd` has been updated to latest version from [here](https://github.com/tdwg/abcd)

Anyway, although #285 suggests you have no interest, #395 and #413 suggest that you may want to see this at least.

### CODE REVIEW

**Comment by mfrasca** [comment]
thank you for this pull request!
I see I don't manage to make myself understood on the point whether I'm interested or not in XSL.
should I try again?
it's several years that I've been asking for examples and documentation, and you sort of announced both.  now I'm moving things in this part of the code, and I still have no documentation and hardly any examples and actually not a single unit test for the XSL formatter.
I've been working with the Mako formatter and I know how to produce svg labels, postscript, html, csv, and how to achieve a quite decent graphic result, and a very broad range of usages.  From what I see in the XSL results (unattractive, simplistic, stiff, limited), there's very little point in keeping both things.  I'm sure you have a different opinion, but will you share docs and models?  about models, you said a very sharp **NO** some time ago.
so:
- I need documentation to make sure I don't change things for users counting on the XSL formatter.
- I would like decent XSL examples, showing that you can at achieve a typesetting result at least comparable to what I can offer with Mako, and motivating me to keeping this formatter.

right.  I'm now having a look at the contents of your pull-request.

**Review by mfrasca — CHANGES_REQUESTED** [review]
please add some documentation.  if you have zero time for it, please do at least provide a couple of pictures showing the intended labels.
you added a function in utils, what about a couple of examples, doctest would suffice, even just a couple of significant 'input/output' cases.

**Comment by RoDuth** [comment]
There is a unit test in `bauble/test/test_utils.py` for the function in utils.  
If I'm to be honest, after #109 I have little desire to bother writing documentation again, but also nor do I have the time right now.

images of the sort of output:
`label_example.xsl` one page example.
screen shot 2018-09-25 at 9 51 24 pm

`label_memorial_example.xsl` using a single accession.
screen shot 2018-09-25 at 6 12 28 am

`list_notes(abcd).xsl`
screen shot 2018-09-25 at 8 32 06 pm

`list_notes.xsl`
screen shot 2018-09-25 at 8 27 52 pm

**Comment by mfrasca** [comment]
I might be confusing, but I thought I was reviewing and not willing to accept your **technical** documentation, because you were interpreting definitions in a way which felt wrong to me, and difficult to integrate with the rest.  in the end, I've accepted your contributions and integrated it in the process, and documented it.  If we managed not to "alienate users", you can tell.
I'm trying to get you to contribute some **user** documentation.  and it's not me who particularly cares for this: whatever remains undefined, I will not know how to keep functional.

btw: I hadn't noticed before, but this is a pull request on 1.0, and I'm only backporting to 1.0.

**Comment by mfrasca** [comment]
thank you for the examples and XSL templates, I'll see what I can do to pull them into 3.1.
unless you want to have a look there and open a pull request on that line?

**Comment by RoDuth** [comment]
I can't get 3.1 to work on either mac os or windows.  The 2 OSes I am currently using.  Until that's resolved its of little use to me, by your own admission #419
> at the moment, the 3.1 line is not production-ready,

**Comment by mfrasca** [comment]
hey, are you blaming me for not managing to deliver 3.1?  :rofl: 
without Windows help, there it will stay you know!

**Comment by RoDuth** [comment]
no, just pointing out that I can't use 3.1 easily right now and the people at MRBG can't use it at all so I'm unlikely to do anything there other than try to get it to actual run right at this moment.  You are losing a lot of potential users by not having it run on windows and osx (see [here](https://en.wikipedia.org/wiki/Usage_share_of_operating_systems#Desktop_and_laptop_computers)) Adding new features to 3.1 makes little sense to me right now.  

You were asking about xsl, if you were to have merged this you could have seen for yourself the ways I have been using it.

**Comment by mfrasca** [comment]
thank you, I have an idea now, also thanks to the images you provided.  as I wrote, I'll have a look at them in the 3.1 line which is where I'm doing any new development.
I would organize the templates differently, however.  like they were `resources`, so in a separate directory.  cf `mako/templates`.  and although I consider reasonable what you did, putting pictures in separate directories, it has the limitation that you cannot share resources among templates, so I would not do that.

I'm still puzzled about the "lot of potential users" you keep mentioning.

**Comment by RoDuth** [comment]
Originally I had used absolute paths in the template (and you still can do that) but that made it hard to share templates with the MRBG.  I had tried adding a 'add image' FileChooserButton to the 'report options' window but found it annoying to have to remember to add the file each time I changed templates.  Then came the day I had a template with a few images on it, I had originally gone with a FileChooserDialog but realised that I was putting all files for each template in one folder (even if they were also used in another template) and selecting them all, that's when I decided to use the folder approach, I no longer had to do anything, it just worked.  Plus it was really easy to share templates.  I no longer had to use absolute paths or complete any extra steps in the 'report options' window.

This is a paradigm I was used to for a few things including downloaded web pages (i.e. in Firefox when you 'save page as' it save the pages as `foo.html` and all the other parts in a `foo_files` directory.)

> lot of potential users

anyone who uses windows or osx and has a need to record a collection of plants was my point.

**Comment by mfrasca** [comment]
they can use 1.0, and if they want 3.1 they can sponsor the project.

**Comment by mfrasca** [comment]
they can use 1.0, and if they want 3.1 they can sponsor the project.

**Pull request closed without merging**
