### PR TITLE
Ghini mako reports

### PR DESCRIPTION
**Pull request by RoDuth**
Adds missing source options to mako report system.  Generates less 'Can't get X from Y' exceptions allowing templates to be used in a more generic way regardless of the source of the search.

### CODE REVIEW

**Comment by RoDuth** [comment]
Fair call on the txt to csv.  Didn't _actually_ mean to include it, :disappointed: found its way in when cherry-picking my commits, from while I was away, back onto latest when I got back in range.  Shouldn't do these things late at night but seems to be the only time I get nowadays!  Happy to drop it but can you see any issues?  Its really not a big one but the thinking was from a while ago when I left a few people with working copies of Bauble to look at (back when I was trying to get BGANZ interested), I had a couple of comments from people getting confused about getting "all these text files" when they'd asked for a csv export. (I did point out this isn't the really what its for and pointed them to the reports but they still couldn't get their heads around why csv came out as text files)

I hadn't seen #242 so wasn't aware you had been doing anything related...  (You had closed the issue and marked it as low priority after all!).  I'm not sure I understanding some of your other comments?  Maybe I need to see a use case example for this:

> the missing plural ( `get_objects_pertinent_to` )

or are you saying I missed something in `_get_objects_pertinent_to` ?
and further explanation of these:

> the coding style, it's really ugly

> bad design, because we're "decapsulating" behaviour

I think I have some idea what your saying but could be way of the mark.

For now, with what little time I get for it, I'm in windows world, (Definitely not as comfortable here, tend not to bother checking emails etc..) so not sure when I'll be back to look at this.

**Comment by mfrasca** [comment]
> people getting confused about getting "all these text files" when they'd asked for a csv export

the name csv export is misleading. if you want a csv export, you use a report.

**Comment by mfrasca** [comment]
I also don't know when to look at this, you don't really **need** it, do you? I mean, this code is already in your branch.
as for mentioning you in the copyright, I think I should already include you in some of the files I wrote after you and @tmyersdn gave hints. if you care to look for them, I will correct the situation.

**Comment by RoDuth** [comment]
No problem, it's fine in my branch, just making sure I share.

I had seen the upgrade scripts but thought them likely irrelevant as anything coming from a version <1.0 would be exported as txt.  It would only be after getting your data into 1.0 that it would become csv.  And yes, the name is as much the root of the issue as anything.  But now I'm discussing something I don't really care about!

**Comment by mfrasca** [comment]
>  It would only be after getting your data into 1.0 that it would become csv

you see, ghini and bauble 1.0 count on an import-export from-to csv files named as `txt`.
the destructive initialization of the database can be done with an export from an other installation, or from the default values found in the [plants plugin[(https://github.com/Ghini/ghini.desktop/tree/ghini-1.0-dev/bauble/plugins/plants/default).
changing the export from `txt` to `csv` would break this. you would have some 1.0 installations producing `txt` exports, some producing `csv` exports. your branch needs to import from `csv` files in order to keep any sort of usefulness of this export. and once you do that, you also need to rename the `default` files.
I see this change as important as a change in the database, something we can discuss, but which I will not include within one production line.
ghini-1.0 and bauble-1.0 work with `txt` files form import and export; we can decide that starting from 1.1 ghini works with `csv` files for this, but this would include the migration script, the `default` files, the import and, finally, the export, which is the only part you changed.

**Comment by RoDuth** [comment]
Done.

Must admit, after sending that this morning I walked out the door and thought of export/import from a slightly older version to a current version...

**Comment by mfrasca** [comment]
thanks, I will look into the rest of the proposed changes. I'm not sure when I will have time, I'm in the middle of a relocation, from a rather stable home to travelling again.

**Comment by RoDuth** [comment]
Not a problem.

You're no longer at JBQ then??

**Comment by RoDuth** [comment]
Not a problem.

You're no longer at JBQ then??

**Comment by mfrasca** [comment]
it was a short, very intensive cooperation. definitely very productive for me, and for the JBQ too, if I correctly interpret their feedback. I'm travelling again, looking for a next garden.

**Comment by RoDuth** [comment]
Looking at something completely unrelated and realised I'd made a mistake... It was get_locations.. in your original version all along, not get_location..  Have put it back.

**Comment by mfrasca** [comment]
this is what I meant, a bit too cryptically, by "the rest looks acceptable, but for the missing plural"

**Comment by mfrasca** [comment]
screenshot from 2017-09-27 14-58-55

**Pull request merged**
