### PR TITLE
windows installer

### PR DESCRIPTION
**Pull request by RoDuth**
For consideration...  (Most of this is from around a year ago...)

On a windows machine with NSIS v3 plus NsisMultiUser, nsisunz, Inetc and MD5 plugins installed.  From a working copy of ghini with the virtual environment activated.
```
python setup.py py2exe
makensis scripts\build-multiuser.nsi
```
Creates an installer in the scripts directory.

Can send you my latest version if you like.

Could use [github releases](https://help.github.com/articles/about-releases/) to distribute?  (Possibly with the MRBG branch version from my fork to avoid confusion?)

Addresses #126 #109

### CODE REVIEW

**Comment by RoDuth** [comment]
Or had I actually sent this to you before?  Didn't think I had but just noticed a previous PR?  Not sure how different it is but I did clean it up recently before building the installer and this version is not built on the MRBG branch.

**Comment by RoDuth** [comment]
I'm not 100% sure (will try looking into it a little more later) but I'd say that the new file `build-multiuser.nsi` would be the main culprit.  Its fairly large and I couldn't find a viable way to test it... I don't think there is one.

**Comment by mfrasca** [comment]
`*.nsi` aren't included in the coverage report. the report shows this:
image

**Comment by RoDuth** [comment]
Was it just those 2?

Not sure what to do about updates for windows installer.  More than anything I see it as a way to try before you buy in to the whole git install.  But then in government settings, here at least, there is no way they'll allow a git install process on user machines...  Maybe the installer should be something that is released every say 10 or 12 minor versions or something?

If you want to try out the installer itself I put the MRBG version [here](https://github.com/RoDuth/ghini.desktop/releases/tag/v1.0.72-mrbg) as a release on my fork.  Figured it best to hide this version on my fork to avoid the risk of confusion, at least for now anyway.  Is this the best way to distribute?  I can put up a ghini-1.0 version also if you want me to or send it to you.  

Also, I noticed that there has been ['Major Changes'](https://github.com/Drizin/NsisMultiUser/commit/0226b2f3913afb58a40c32eedb0a8fcc59ab15a3) to the NsisMultiUser plugin that the script relies on.  Its since I installed it so don't know what effect it could have if you do try to build it yourself.

**Comment by mfrasca** [comment]
I had to revert this. I'm not going to accept pull requests directly into the production line `ghini-1.0`. please redo, but target `ghini-1.0-dev`. thank you and sorry for not having noticed this earlier.

**Comment by RoDuth** [comment]
I know about pep8 now but didn't a year ago I'll admit.  And I didn't check it recently either I'll admit!

Ah... yes. Sorry, wasn't sure which target to use.  Now I know.  Will resend.

**Comment by mfrasca** [comment]
actually, not necessary, I can merge the same line (the one you produced) from the command line.
and review before committing, and choose myself the target.

**Comment by mfrasca** [comment]
why are many of the variables in the new `scripts/build-multiuser.nsi` all UPPERCASE?

**Comment by RoDuth** [comment]
Sorry. domestic activities got in the way straight after starting this.  Give me half an hour.

I think the NSIS variable names depend on whatever the plugins call them.  Remember thinking that it seemed to be something like: straight NSIS is always lower case and plugin variables - especially if they override the default - are capitalised.  So for instance `!define version` is default NSIS `!define VERSION` is how the NsisMultiUser plugin captures the variable before eventually passing it on as the NSIS version.)

Will change Add_to_PATH to add_to_path.

**Comment by RoDuth** [comment]
I'm sending the pull request but am still in linux and haven't done a test run in windows just yet so maybe still wait 30 mins.

**Comment by RoDuth** [comment]
Sorry... I see my last comment was 2 hours ago, I forgot that windows takes at least 30mins just to boot! 😢  
Let alone fire up a VM to test the installer on a blank (win7) setup...

**Comment by RoDuth** [comment]
I think it was `python setup.py install` see [this](https://stackoverflow.com/questions/20104368/using-py2exe-in-a-virtualenv) SO answer.  I know I have had to have visual studio (community edition) install for various reasons, this may have been the first?

**Pull request merged**
